 
LEADER_PORT = "COM3"
FOLLOWER_PORT = "COM4"

BAUDRATE = 1000000
PROTOCOL_VERSION = 1.0

LEADER_IDS = [1, 2, 3, 4, 5, 6]
FOLLOWER_IDS = [1, 2, 3, 4, 5, 6]

#addresses
ADDR_TORQUE = 24

ADDR_GOAL_POSITION = 30
LEN_GOAL_POSITION = 2

ADDR_MOVING_SPEED = 32
LEN_MOVING_SPEED = 2

ADDR_PRESENT_POSITION = 36
LEN_PRESENT_POSITION = 2

ADDR_PRESENT_SPEED = 38
LEN_PRESENT_SPEED = 2

ADDR_PRESENT_LOAD = 40
LEN_PRESENT_LOAD = 2

ADDR_PRESENT_VOLTAGE = 42
LEN_PRESENT_VOLTAGE = 1

ADDR_PRESENT_TEMPERATURE = 43
LEN_PRESENT_TEMPERATURE = 1

TORQUE_ENABLE = 1
TORQUE_DISABLE = 0

MIN_POSITION = 0
MAX_POSITION = 1023